PC:
  NAME: "nvidia"
  IP: 192.168.0.112
  FORCE_SENSOR_PUB_PORT: 6559

NUC:
  NAME: "charmander"
  IP: 192.168.0.115
  PUB_PORT: 6556
  SUB_PORT: 6555
  GRIPPER_PUB_PORT: 6558
  GRIPPER_SUB_PORT: 6557

ROBOT:
  IP: 172.18.1.2

CONTROL:
  STATE_PUBLISHER_RATE: 100
  POLICY_RATE: 80
  FORCE_SENSOR_RATE: 100
  TRAJ_RATE: 500
  ZMQ_NOBLOCK: true

ARM_LOGGER:
  CONSOLE:
    LOGGER_NAME: "arm_logger"
    LEVEL: "debug"
    USE: true
  FILE:
    LOGGER_NAME: "logs/deoxys_control_arm_program.log"
    LEVEL: "debug"
    USE: true

GRIPPER_LOGGER:
  CONSOLE:
    LOGGER_NAME: "gripper_logger"
    LEVEL: "info"
    USE: true
  FILE:
    LOGGER_NAME: "logs/deoxys_control_gripper_program.log"
    LEVEL: "debug"
    USE: true
